### ISSUE TITLE
Criar README

### ISSUE THREAD

**Issue by LuizGMiranda** [octo-ead/front#5]
Criar README inicial e simples para o projeto.

**Comment by rafaelmenon** [comment]
Luiz se você quiser pode criar esse conforme tinha conversado com você no começo!

**Comment by LuizGMiranda** [comment]
@rafaelmenon pode pegar a issue :D

**Comment by Verossim** [comment]
O README vai em português ou em inglês?

**Comment by LuizGMiranda** [comment]
Acho mais interessante ser primeiro em português e depois colocar em inglês.

**Comment by rafaelmenon** [comment]
Será em português Matheus
